// src/components/workspaces/WorkspaceTabBar.tsx
import React, { useState, useCallback, useEffect } from 'react';
import { useWorkspaceStore } from '../../stores/workspaceStore';
import { LayoutSelector } from './LayoutSelector';
import { WorkspaceCreationModal } from './WorkspaceCreationModal';
import './WorkspaceTabBar.css';

interface ContextMenuProps {
  x: number;
  y: number;
  workspaceId: string;
  onClose: () => void;
  onDelete: (id: string) => void;
  onRename: (id: string) => void;
  onEditLayout: (id: string) => void;
}

interface DeleteConfirmModalProps {
  icon: string;
  title: string;
  description: React.ReactNode;
  confirmText: string;
  onConfirm: () => void;
  onCancel: () => void;
}

interface RenameModalProps {
  workspaceId: string;
  currentName: string;
  onConfirm: (id: string, newName: string) => void;
  onCancel: () => void;
}

const RenameModal: React.FC<RenameModalProps> = ({
  workspaceId,
  currentName,
  onConfirm,
  onCancel,
}) => {
  const [name, setName] = React.useState(currentName);
  const inputRef = React.useRef<HTMLInputElement>(null);

  React.useEffect(() => {
    inputRef.current?.focus();
    inputRef.current?.select();
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (name.trim()) {
      onConfirm(workspaceId, name.trim());
    }
  };

  return (
    <div className="modal-overlay" onClick={onCancel}>
      <div className="rename-modal" onClick={(e) => e.stopPropagation()}>
        <div className="rename-modal-header">
          <span className="rename-modal-icon">✏️</span>
          <h3 className="rename-modal-title">Rename Workspace</h3>
        </div>
        <form onSubmit={handleSubmit}>
          <input
            ref={inputRef}
            type="text"
            className="rename-input"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Enter workspace name"
            maxLength={50}
          />
          <div className="rename-modal-actions">
            <button type="button" className="btn-cancel" onClick={onCancel}>
              Cancel
            </button>
            <button type="submit" className="btn-rename" disabled={!name.trim()}>
              Rename
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

const DeleteConfirmModal: React.FC<DeleteConfirmModalProps> = ({
  icon,
  title,
  description,
  confirmText,
  onConfirm,
  onCancel,
}) => {
  return (
    <div className="modal-overlay" onClick={onCancel}>
      <div className="delete-modal" onClick={(e) => e.stopPropagation()}>
        <div className="delete-modal-icon-wrapper">
          <span className="delete-modal-icon">{icon}</span>
        </div>
        <h3 className="delete-modal-title">{title}</h3>
        <p className="delete-modal-description">{description}</p>
        <div className="delete-modal-actions">
          <button className="btn-cancel" onClick={onCancel}>
            Cancel
          </button>
          <button className="btn-delete" onClick={onConfirm}>
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
};

export const ContextMenu: React.FC<ContextMenuProps> = ({
  x,
  y,
  workspaceId,
  onClose,
  onDelete,
  onRename,
  onEditLayout,
}) => {
  return (
    <div
      className="context-menu"
      style={{ top: y, left: x }}
      role="menu"
      aria-label="Workspace actions"
    >
      <div
        className="context-menu-item"
        onClick={(e) => {
          e.stopPropagation();
          e.preventDefault();
          onEditLayout(workspaceId);
          onClose();
        }}
        role="menuitem"
      >
        <span className="context-menu-icon settings">⚙️</span>
        <span>Edit Layout</span>
      </div>
      <div
        className="context-menu-item"
        onClick={(e) => {
          e.stopPropagation();
          e.preventDefault();
          onRename(workspaceId);
          onClose();
        }}
        role="menuitem"
      >
        <span className="context-menu-icon edit">✏️</span>
        <span>Rename</span>
      </div>
      <div className="context-menu-divider" />
      <div
        className="context-menu-item danger"
        onClick={(e) => {
          e.stopPropagation();
          e.preventDefault();
          onDelete(workspaceId);
          onClose();
        }}
        role="menuitem"
      >
        <span className="context-menu-icon delete">🗑️</span>
        <span>Delete</span>
      </div>
    </div>
  );
};

export const WorkspaceTabBar: React.FC = () => {
  // Individual selectors to prevent re-rendering when unrelated state changes
  const workspaces = useWorkspaceStore((s) => s.workspaces);
  const currentWorkspace = useWorkspaceStore((s) => s.currentWorkspace);
  const theme = useWorkspaceStore((s) => s.theme);
  const isWorkspaceModalOpen = useWorkspaceStore((s) => s.isWorkspaceModalOpen);
  const setCurrentWorkspace = useWorkspaceStore((s) => s.setCurrentWorkspace);
  const removeWorkspace = useWorkspaceStore((s) => s.removeWorkspace);
  const updateWorkspace = useWorkspaceStore((s) => s.updateWorkspace);
  const setWorkspaceModalOpen = useWorkspaceStore((s) => s.setWorkspaceModalOpen);
  const setTheme = useWorkspaceStore((s) => s.setTheme);
  const setWorkspaceModalOpenWithEdit = useWorkspaceStore((s) => s.setWorkspaceModalOpenWithEdit);
  const reorderWorkspaces = useWorkspaceStore((s) => s.reorderWorkspaces);
  const [contextMenu, setContextMenu] = useState<{
    x: number;
    y: number;
    workspaceId: string;
  } | null>(null);

  // Drag and drop state
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dropTargetIndex, setDropTargetIndex] = useState<number | null>(null);
  const tabsContainerRef = React.useRef<HTMLDivElement>(null);
  const [deleteModal, setDeleteModal] = useState<{
    isOpen: boolean;
    workspaceId: string;
    workspaceName: string;
  } | null>(null);
  const [renameModal, setRenameModal] = useState<{
    workspaceId: string;
    currentName: string;
  } | null>(null);

  const handleContextMenu = useCallback((e: React.MouseEvent, workspaceId: string) => {
    e.preventDefault();
    e.stopPropagation();
    setContextMenu({
      x: e.clientX,
      y: e.clientY,
      workspaceId,
    });
  }, []);

  const requestDelete = useCallback((id: string, name: string) => {
    setDeleteModal({ isOpen: true, workspaceId: id, workspaceName: name });
    setContextMenu(null);
  }, []);

  const confirmDelete = useCallback(() => {
    if (deleteModal) {
      removeWorkspace(deleteModal.workspaceId);
      setDeleteModal(null);
    }
  }, [deleteModal, removeWorkspace]);

  const cancelDelete = useCallback(() => {
    setDeleteModal(null);
  }, []);

  const handleRename = useCallback((id: string) => {
    const workspace = workspaces.find(ws => ws.id === id);
    if (!workspace) return;

    setRenameModal({
      workspaceId: id,
      currentName: workspace.name,
    });
    setContextMenu(null);
  }, [workspaces]);

  const confirmRename = useCallback((id: string, newName: string) => {
    updateWorkspace(id, { name: newName });
    setRenameModal(null);
  }, [updateWorkspace]);

  const cancelRename = useCallback(() => {
    setRenameModal(null);
  }, []);

  const handleEditLayout = useCallback((id: string) => {
    const workspace = workspaces.find(ws => ws.id === id);
    if (!workspace) return;

    setWorkspaceModalOpenWithEdit(workspace);
    setContextMenu(null);
  }, [workspaces, setWorkspaceModalOpenWithEdit]);

  const handleDeleteAll = useCallback(() => {
    setDeleteModal({ isOpen: true, workspaceId: 'ALL', workspaceName: 'all workspaces' });
  }, []);

  const confirmDeleteAll = useCallback(() => {
    const idsToDelete = workspaces.map(ws => ws.id);
    idsToDelete.forEach(id => removeWorkspace(id));
    setDeleteModal(null);
  }, [workspaces, removeWorkspace]);

  const closeContextMenu = useCallback(() => {
    setContextMenu(null);
  }, []);

  useEffect(() => {
    const handleClickOutside = () => {
      closeContextMenu();
      setRenameModal(null);
    };
    if (contextMenu) {
      document.addEventListener('click', handleClickOutside);
      return () => document.removeEventListener('click', handleClickOutside);
    }
  }, [contextMenu, closeContextMenu]);

  const handleWorkspaceClick = useCallback((workspaceId: string) => {
    const ws = workspaces.find(w => w.id === workspaceId);
    setCurrentWorkspace(ws!);
  }, [workspaces, setCurrentWorkspace]);

  // Drag and drop handlers
  const handleDragStart = useCallback((index: number) => {
    setDraggedIndex(index);
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent, index: number) => {
    e.preventDefault();
    if (draggedIndex === null || draggedIndex === index) return;
    setDropTargetIndex(index);
  }, [draggedIndex]);

  const handleDragLeave = useCallback(() => {
    setDropTargetIndex(null);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    if (draggedIndex === null || draggedIndex === dropIndex) {
      setDraggedIndex(null);
      setDropTargetIndex(null);
      return;
    }
    reorderWorkspaces(draggedIndex, dropIndex);
    setDraggedIndex(null);
    setDropTargetIndex(null);
  }, [draggedIndex, reorderWorkspaces]);

  const handleDragEnd = useCallback(() => {
    setDraggedIndex(null);
    setDropTargetIndex(null);
  }, []);

  const isDeleteAll = deleteModal?.workspaceId === 'ALL';

  const getTerminalCount = useCallback((workspaceId: string) => {
    const workspace = workspaces.find(ws => ws.id === workspaceId);
    return workspace?.terminals?.length || 0;
  }, [workspaces]);

  const totalTerminals = workspaces.filter(Boolean).reduce((acc, ws) => acc + getTerminalCount(ws.id), 0);

  return (
    <>
      <div className="workspace-tab-bar">
        <div className="tabs-container" ref={tabsContainerRef} role="tablist" aria-label="Workspaces">
          {workspaces.filter(Boolean).map((workspace, index) => {
            const isActive = currentWorkspace?.id === workspace.id;
            const terminalCount = getTerminalCount(workspace.id);
            const isDragging = draggedIndex === index;
            const isDropTarget = dropTargetIndex === index;

            return (
              <React.Fragment key={workspace.id}>
                {isDropTarget && draggedIndex !== null && draggedIndex < index && (
                  <div className="drop-indicator" />
                )}
                <div
                  className={`workspace-tab ${isActive ? 'active' : ''} ${isDragging ? 'dragging' : ''}`}
                  onClick={() => handleWorkspaceClick(workspace.id)}
                  onContextMenu={(e) => handleContextMenu(e, workspace.id)}
                  draggable
                  onDragStart={() => handleDragStart(index)}
                  onDragOver={(e) => handleDragOver(e, index)}
                  onDragLeave={handleDragLeave}
                  onDrop={(e) => handleDrop(e, index)}
                  onDragEnd={handleDragEnd}
                  title={`${workspace.name} - ${terminalCount} terminal${terminalCount !== 1 ? 's' : ''}`}
                  role="tab"
                  aria-selected={isActive}
                  tabIndex={isActive ? 0 : -1}
                >
                  <span className="tab-icon" aria-hidden="true">{workspace.icon || '📁'}</span>
                  <span className="tab-name">{workspace.name}</span>
                  <span className="terminal-badge" aria-label={`${terminalCount} terminal${terminalCount !== 1 ? 's' : ''}`}>
                    {terminalCount}
                  </span>
                  <button
                    className="tab-close-btn"
                    onClick={(e) => {
                      e.stopPropagation();
                      requestDelete(workspace.id, workspace.name);
                    }}
                    title="Delete workspace"
                    aria-label={`Delete ${workspace.name}`}
                  >
                    ×
                  </button>
                </div>
                {isDropTarget && draggedIndex !== null && draggedIndex > index && (
                  <div className="drop-indicator" />
                )}
              </React.Fragment>
            );
          })}

          <button
            className="add-workspace-tab"
            onClick={() => setWorkspaceModalOpen(true)}
            title="New Workspace"
            aria-label="Create new workspace"
          >
            <span className="add-workspace-icon">+</span>
          </button>
        </div>

        <div className="tab-actions">
          {totalTerminals > 0 && (
            <div className="total-count-badge" title={`Total: ${totalTerminals} terminal${totalTerminals !== 1 ? 's' : ''}`}>
              <span className="total-count-icon">📊</span>
              <span className="total-count-number">{totalTerminals}</span>
            </div>
          )}

          {currentWorkspace && (
            <button
              className="action-btn edit-layout-btn"
              onClick={() => setWorkspaceModalOpenWithEdit(currentWorkspace)}
              title="Edit Current Layout"
              aria-label="Edit current workspace layout"
            >
              <span className="btn-icon-settings">⚙️</span>
            </button>
          )}

          {workspaces.length > 1 && (
            <button
              className="action-btn delete-all-btn"
              onClick={handleDeleteAll}
              title="Delete All Workspaces"
              aria-label="Delete all workspaces"
            >
              <span className="btn-icon-delete">🗑️</span>
            </button>
          )}
        </div>
      </div>

      {contextMenu && (
        <ContextMenu
          x={contextMenu.x}
          y={contextMenu.y}
          workspaceId={contextMenu.workspaceId}
          onClose={closeContextMenu}
          onDelete={(id) => {
            const ws = workspaces.find(w => w.id === id);
            if (ws) requestDelete(id, ws.name);
          }}
          onRename={handleRename}
          onEditLayout={handleEditLayout}
        />
      )}

      {renameModal && (
        <RenameModal
          workspaceId={renameModal.workspaceId}
          currentName={renameModal.currentName}
          onConfirm={confirmRename}
          onCancel={cancelRename}
        />
      )}

      {deleteModal && (
        <DeleteConfirmModal
          icon={isDeleteAll ? '⚠️' : '🗑️'}
          title={isDeleteAll ? 'Delete All Workspaces' : 'Delete Workspace'}
          description={
            isDeleteAll ? (
              <>
                Are you sure you want to delete <strong>all {workspaces.length} workspaces</strong>?
                <br />
                This will remove <strong>{totalTerminals} terminals</strong> and cannot be undone.
              </>
            ) : (
              <>
                Are you sure you want to delete <strong>"{deleteModal.workspaceName}"</strong>?
                <br />
                This action cannot be undone.
              </>
            )
          }
          confirmText={isDeleteAll ? 'Delete All' : 'Delete'}
          onConfirm={isDeleteAll ? confirmDeleteAll : confirmDelete}
          onCancel={cancelDelete}
        />
      )}

      {isWorkspaceModalOpen && (
        <WorkspaceCreationModal
          isOpen={isWorkspaceModalOpen}
          onClose={() => setWorkspaceModalOpen(false)}
          editingWorkspace={useWorkspaceStore.getState().editingWorkspace}
        />
      )}
    </>
  );
};

// tdt-space-v3/frontend/src/components/workspaces/WorkspaceTabBar.svelte
<script lang="ts">
  import { workspaceStore } from '../../stores';
  import './WorkspaceTabBar.css';

  // Local state
  let contextMenu = $state<{ x: number; y: number; workspaceId: string } | null>(null);
  let deleteModal = $state<{ isOpen: boolean; workspaceId: string; workspaceName: string } | null>(null);
  let renameModal = $state<{ workspaceId: string; currentName: string } | null>(null);
  let renameInputValue = $state('');

  // Derived state from store
  let workspaces = $derived(workspaceStore.workspaces);
  let currentWorkspace = $derived(workspaceStore.currentWorkspace);
  let isWorkspaceModalOpen = $derived(workspaceStore.isWorkspaceModalOpen);
  let editingWorkspace = $derived(workspaceStore.editingWorkspace);

  let isDeleteAll = $derived(deleteModal?.workspaceId === 'ALL');

  function getTerminalCount(workspaceId: string): number {
    const workspace = workspaces.find(ws => ws.id === workspaceId);
    return workspace?.terminals?.length || 0;
  }

  let totalTerminals = $derived(
    workspaces.filter(Boolean).reduce((acc, ws) => acc + getTerminalCount(ws.id), 0)
  );

  function handleContextMenu(e: MouseEvent, workspaceId: string) {
    e.preventDefault();
    e.stopPropagation();
    contextMenu = { x: e.clientX, y: e.clientY, workspaceId };
  }

  function requestDelete(id: string, name: string) {
    deleteModal = { isOpen: true, workspaceId: id, workspaceName: name };
    contextMenu = null;
  }

  function confirmDelete() {
    if (deleteModal) {
      workspaceStore.removeWorkspace(deleteModal.workspaceId);
      deleteModal = null;
    }
  }

  function cancelDelete() {
    deleteModal = null;
  }

  function handleRename(id: string) {
    const workspace = workspaces.find(ws => ws.id === id);
    if (!workspace) return;
    renameModal = { workspaceId: id, currentName: workspace.name };
    renameInputValue = workspace.name;
    contextMenu = null;
  }

  function confirmRename() {
    if (renameModal && renameInputValue.trim()) {
      workspaceStore.updateWorkspace(renameModal.workspaceId, { name: renameInputValue.trim() });
      renameModal = null;
    }
  }

  function cancelRename() {
    renameModal = null;
  }

  function handleEditLayout(id: string) {
    const workspace = workspaces.find(ws => ws.id === id);
    if (!workspace) return;
    workspaceStore.setWorkspaceModalOpenWithEdit(workspace);
    contextMenu = null;
  }

  function handleDeleteAll() {
    deleteModal = { isOpen: true, workspaceId: 'ALL', workspaceName: 'all workspaces' };
  }

  function confirmDeleteAll() {
    const idsToDelete = workspaces.map(ws => ws.id);
    idsToDelete.forEach(id => workspaceStore.removeWorkspace(id));
    deleteModal = null;
  }

  function closeContextMenu() {
    contextMenu = null;
  }

  function handleWorkspaceClick(workspaceId: string) {
    const ws = workspaces.find(w => w.id === workspaceId);
    if (ws) {
      workspaceStore.setCurrentWorkspace(ws);
    }
  }

  // Close context menu on click outside
  $effect(() => {
    if (contextMenu) {
      const handleClick = () => {
        closeContextMenu();
        renameModal = null;
      };
      document.addEventListener('click', handleClick);
      return () => document.removeEventListener('click', handleClick);
    }
  });
</script>

<div class="workspace-tab-bar">
  <div class="tabs-container" role="tablist" aria-label="Workspaces">
    {#each workspaces.filter(Boolean) as workspace (workspace.id)}
      {@const isActive = currentWorkspace?.id === workspace.id}
      {@const terminalCount = getTerminalCount(workspace.id)}
      <div
        class="workspace-tab"
        class:active={isActive}
        onclick={() => handleWorkspaceClick(workspace.id)}
        oncontextmenu={(e) => handleContextMenu(e, workspace.id)}
        title="{workspace.name} - {terminalCount} terminal{terminalCount !== 1 ? 's' : ''}"
        role="tab"
        aria-selected={isActive}
        tabindex={isActive ? 0 : -1}
      >
        <span class="tab-icon" aria-hidden="true">{workspace.icon || '📁'}</span>
        <span class="tab-name">{workspace.name}</span>
        <span class="terminal-badge" aria-label="{terminalCount} terminal{terminalCount !== 1 ? 's' : ''}">
          {terminalCount}
        </span>
        <button
          class="tab-close-btn"
          onclick={(e) => {
            e.stopPropagation();
            requestDelete(workspace.id, workspace.name);
          }}
          title="Delete workspace"
          aria-label="Delete {workspace.name}"
        >
          ×
        </button>
      </div>
    {/each}

    <button
      class="add-workspace-tab"
      onclick={() => workspaceStore.setWorkspaceModalOpen(true)}
      title="New Workspace"
      aria-label="Create new workspace"
    >
      <span class="add-workspace-icon">+</span>
    </button>
  </div>

  <div class="tab-actions">
    {#if totalTerminals > 0}
      <div class="total-count-badge" title="Total: {totalTerminals} terminal{totalTerminals !== 1 ? 's' : ''}">
        <span class="total-count-icon">📊</span>
        <span class="total-count-number">{totalTerminals}</span>
      </div>
    {/if}

    {#if currentWorkspace}
      <button
        class="action-btn edit-layout-btn"
        onclick={() => workspaceStore.setWorkspaceModalOpenWithEdit(currentWorkspace)}
        title="Edit Current Layout"
        aria-label="Edit current workspace layout"
      >
        <span class="btn-icon-settings">⚙️</span>
      </button>
    {/if}

    {#if workspaces.length > 1}
      <button
        class="action-btn delete-all-btn"
        onclick={handleDeleteAll}
        title="Delete All Workspaces"
        aria-label="Delete all workspaces"
      >
        <span class="btn-icon-delete">🗑️</span>
      </button>
    {/if}
  </div>
</div>

<!-- Context Menu -->
{#if contextMenu}
  <div
    class="context-menu"
    style="top: {contextMenu.y}px; left: {contextMenu.x}px;"
    role="menu"
    aria-label="Workspace actions"
  >
    <div
      class="context-menu-item"
      onclick={(e) => {
        e.stopPropagation();
        e.preventDefault();
        if (contextMenu) handleEditLayout(contextMenu.workspaceId);
      }}
      role="menuitem"
    >
      <span class="context-menu-icon settings">⚙️</span>
      <span>Edit Layout</span>
    </div>
    <div
      class="context-menu-item"
      onclick={(e) => {
        e.stopPropagation();
        e.preventDefault();
        if (contextMenu) handleRename(contextMenu.workspaceId);
      }}
      role="menuitem"
    >
      <span class="context-menu-icon edit">✏️</span>
      <span>Rename</span>
    </div>
    <div class="context-menu-divider" />
    <div
      class="context-menu-item danger"
      onclick={(e) => {
        e.stopPropagation();
        e.preventDefault();
        if (contextMenu) {
          const ws = workspaces.find(w => w.id === contextMenu!.workspaceId);
          if (ws) requestDelete(contextMenu!.workspaceId, ws.name);
        }
      }}
      role="menuitem"
    >
      <span class="context-menu-icon delete">🗑️</span>
      <span>Delete</span>
    </div>
  </div>
{/if}

<!-- Rename Modal -->
{#if renameModal}
  <div class="modal-overlay" onclick={cancelRename}>
    <div class="rename-modal" onclick={(e) => e.stopPropagation()}>
      <div class="rename-modal-header">
        <span class="rename-modal-icon">✏️</span>
        <h3 class="rename-modal-title">Rename Workspace</h3>
      </div>
      <form onsubmit={(e) => { e.preventDefault(); confirmRename(); }}>
        <input
          type="text"
          class="rename-input"
          bind:value={renameInputValue}
          placeholder="Enter workspace name"
          maxlength={50}
          autofocus
        />
        <div class="rename-modal-actions">
          <button type="button" class="btn-cancel" onclick={cancelRename}>
            Cancel
          </button>
          <button type="submit" class="btn-rename" disabled={!renameInputValue.trim()}>
            Rename
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

<!-- Delete Modal -->
{#if deleteModal}
  <div class="modal-overlay" onclick={cancelDelete}>
    <div class="delete-modal" onclick={(e) => e.stopPropagation()}>
      <div class="delete-modal-icon-wrapper">
        <span class="delete-modal-icon">{isDeleteAll ? '⚠️' : '🗑️'}</span>
      </div>
      <h3 class="delete-modal-title">{isDeleteAll ? 'Delete All Workspaces' : 'Delete Workspace'}</h3>
      <p class="delete-modal-description">
        {#if isDeleteAll}
          Are you sure you want to delete <strong>all {workspaces.length} workspaces</strong>?<br />
          This will remove <strong>{totalTerminals} terminals</strong> and cannot be undone.
        {:else}
          Are you sure you want to delete <strong>"{deleteModal.workspaceName}"</strong>?<br />
          This action cannot be undone.
        {/if}
      </p>
      <div class="delete-modal-actions">
        <button class="btn-cancel" onclick={cancelDelete}>
          Cancel
        </button>
        <button class="btn-delete" onclick={isDeleteAll ? confirmDeleteAll : confirmDelete}>
          {isDeleteAll ? 'Delete All' : 'Delete'}
        </button>
      </div>
    </div>
  </div>
{/if}
