// tdt-space-v3/frontend/src/components/workspaces/WorkspaceCreationModal.svelte
<script lang="ts">
  import { workspaceStore } from '../../stores';
  import type { Template, WorkspaceCreationConfig } from '../../types/workspace';
  import type { AgentType, AgentConfig } from '../../types/agent';
  import { backendAPI } from '../../services/wails-bridge';
  import AgentItem from './AgentItem.svelte';

  interface Props {
    isOpen: boolean;
    onClose: () => void;
    editingWorkspace?: any;
  }

  let { isOpen, onClose, editingWorkspace = null }: Props = $props();

  const emojis = ['📁', '📂', '💼', '🗂️', '📊', '📈', '💻', '⚡', '🔥', '🚀', '🎯', '⭐', '🔷', '🔶', '💎', '🎨'];
  
  // Agent configurations with proper AgentType values
  const AGENT_CONFIGS: { type: AgentType; name: string; icon: string }[] = [
    { type: 'claude-code', name: 'Claude Code', icon: '🟣' },
    { type: 'opencode', name: 'OpenCode', icon: '🔵' },
    { type: 'droid', name: 'Droid', icon: '🟢' },
    { type: 'codex', name: 'Codex', icon: '🟡' },
    { type: 'cursor', name: 'Cursor', icon: '🔷' },
    { type: 'gemini-cli', name: 'Gemini CLI', icon: '💎' },
    { type: 'aider', name: 'Aider', icon: '🟠' },
    { type: 'goose', name: 'Goose', icon: '🪿' },
    { type: 'oh-my-pi', name: 'Oh My Pi', icon: '🥧' },
    { type: 'warp', name: 'Warp', icon: '⚡' },
    { type: 'amp', name: 'Amp', icon: '🔌' },
    { type: 'kiro', name: 'Kiro', icon: '🎯' },
  ];

  const builtinTemplates = [
    { id: 'single', name: 'Single', columns: 1, rows: 1, icon: '①' },
    { id: 'dual', name: 'Dual', columns: 2, rows: 1, icon: '②' },
    { id: 'quad', name: 'Quad', columns: 2, rows: 2, icon: '④' },
    { id: 'six', name: 'Six', columns: 3, rows: 2, icon: '⑥' },
    { id: 'eight', name: 'Eight', columns: 4, rows: 2, icon: '⑧' },
  ];

  let currentStep = $state<'template' | 'configure'>('template');
  let selectedTemplate = $state<Template | null>(null);
  let workspaceName = $state('My Workspace');
  let selectedIcon = $state(emojis[0]);
  let workingDir = $state('');
  let columns = $state(2);
  let rows = $state(2);
  
  // Agent assignments for each slot (index -> AgentType | null)
  let slotAssignments = $state<(AgentType | null)[]>([]);

  $effect(() => {
    if (editingWorkspace) {
      workspaceName = editingWorkspace.name;
      selectedIcon = editingWorkspace.icon || emojis[0];
      columns = editingWorkspace.columns;
      rows = editingWorkspace.rows;
      selectedTemplate = null;
      currentStep = 'configure';
    }
  });
  
  $effect(() => {
    // Reset slot assignments when layout changes
    const totalSlots = columns * rows;
    slotAssignments = Array(totalSlots).fill(null);
  });

  function selectTemplate(template: typeof builtinTemplates[0]) {
    selectedTemplate = template as unknown as Template;
    columns = template.columns;
    rows = template.rows;
    currentStep = 'configure';
  }
  
  function handleDragStart(e: DragEvent, agentType: AgentType) {
    e.dataTransfer?.setData('application/json', JSON.stringify({ type: agentType }));
    e.dataTransfer!.effectAllowed = 'copy';
  }
  
  function handleDropOnSlot(e: DragEvent, slotIndex: number) {
    e.preventDefault();
    const data = e.dataTransfer?.getData('application/json');
    if (data) {
      const { type } = JSON.parse(data);
      slotAssignments[slotIndex] = type as AgentType;
      slotAssignments = [...slotAssignments];
    }
  }
  
  function handleSlotClick(slotIndex: number) {
    slotAssignments[slotIndex] = null;
    slotAssignments = [...slotAssignments];
  }
  
  function handleAutoDistribute() {
    // Distribute agents evenly across slots
    const totalSlots = columns * rows;
    const agentTypes = AGENT_CONFIGS.map(a => a.type);
    
    slotAssignments = slotAssignments.map((_, i) => {
      return agentTypes[i % agentTypes.length];
    });
  }
  
  function clearAllAgents() {
    slotAssignments = Array(columns * rows).fill(null);
  }

  async function browseDirectory() {
    try {
      // Check if backendAPI has showOpenDialog
      const result = await (backendAPI as any).showOpenDialog?.({
        title: 'Select Working Directory',
        properties: ['openDirectory'],
        defaultPath: workingDir || undefined,
      });
      
      if (result && !result.canceled && result.filePaths.length > 0) {
        workingDir = result.filePaths[0];
      }
    } catch (err) {
      console.error('Failed to browse directory:', err);
      // Fallback: use native file input
      const input = document.createElement('input');
      input.type = 'file';
      input.webkitdirectory = true;
      input.onchange = (e) => {
        const files = (e.target as HTMLInputElement).files;
        if (files && files.length > 0) {
          // Get directory path from first file
          const path = (files[0] as any).path || files[0].webkitRelativePath;
          if (path) {
            workingDir = path.split('/').slice(0, -1).join('/');
          }
        }
      };
      input.click();
    }
  }

  async function handleCreateWorkspace() {
    // Build agent assignments for slots that have agents
    const agentAssignments: Record<string, AgentConfig> = {};
    slotAssignments.forEach((agentType, index) => {
      if (agentType) {
        agentAssignments[`term-${index}`] = {
          type: agentType,
          enabled: true,
        };
      }
    });

    const config: WorkspaceCreationConfig = {
      name: workspaceName,
      columns,
      rows,
      cwd: workingDir || './',
      icon: selectedIcon,
      agentAssignments,
    };

    try {
      if (editingWorkspace) {
        await workspaceStore.updateWorkspace(editingWorkspace.id, {
          name: workspaceName,
          icon: selectedIcon,
          columns,
          rows,
        });
      } else {
        await workspaceStore.addWorkspace(config);
      }
      onClose();
      resetForm();
    } catch (err) {
      console.error('Failed to create/update workspace:', err);
      alert('Failed to create workspace: ' + (err as Error).message);
    }
  }

  function resetForm() {
    currentStep = 'template';
    selectedTemplate = null;
    workspaceName = 'My Workspace';
    selectedIcon = emojis[0];
    workingDir = '';
    columns = 2;
    rows = 2;
    slotAssignments = [];
  }

  function handleClose() {
    onClose();
    resetForm();
  }

  function goBack() {
    if (currentStep === 'configure') {
      currentStep = 'template';
    }
  }
  
  function getAgentCount(type: AgentType): number {
    return slotAssignments.filter(a => a === type).length;
  }
  
  function incrementAgent(type: AgentType) {
    // Find first empty slot
    const emptyIndex = slotAssignments.findIndex(a => a === null);
    if (emptyIndex !== -1) {
      slotAssignments[emptyIndex] = type;
      slotAssignments = [...slotAssignments];
    }
  }
  
  function decrementAgent(type: AgentType) {
    // Find last slot with this agent
    const lastIndex = slotAssignments.lastIndexOf(type);
    if (lastIndex !== -1) {
      slotAssignments[lastIndex] = null;
      slotAssignments = [...slotAssignments];
    }
  }
</script>

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
  <div class="modal-overlay" onclick={handleClose} role="dialog" aria-modal="true" tabindex="-1">
    <div class="creation-modal" onclick={(e) => e.stopPropagation()} role="dialog" aria-modal="true" tabindex="-1">
      <div class="modal-header">
        <h3 id="creation-modal-title">{editingWorkspace ? 'Edit Workspace' : 'Create New Workspace'}</h3>
        <button class="close-btn" onclick={handleClose} aria-label="Close">×</button>
      </div>

      {#if currentStep === 'template'}
        <div class="step-content">
          <p class="step-description">Choose a template for your workspace:</p>
          <div class="template-grid">
            {#each builtinTemplates as template}
              <button
                class="template-card"
                class:selected={selectedTemplate?.id === template.id}
                onclick={() => selectTemplate(template)}
              >
                <span class="template-icon">{template.icon}</span>
                <span class="template-name">{template.name}</span>
                <span class="template-layout">{template.columns}×{template.rows}</span>
              </button>
            {/each}
          </div>
        </div>
      {:else if currentStep === 'configure'}
        <div class="step-content configure-step">
          <div class="configure-layout">
            <!-- Left: Basic Settings -->
            <div class="settings-panel">
              <div class="form-group">
                <label for="workspace-name">Workspace Name</label>
                <input id="workspace-name" type="text" bind:value={workspaceName} placeholder="My Workspace" />
              </div>

              <div class="form-group">
                <span id="workspace-icon-label" class="field-label">Icon</span>
                <div class="icon-grid" role="group" aria-labelledby="workspace-icon-label">
                  {#each emojis as emoji}
                    <button
                      class="icon-btn"
                      class:selected={selectedIcon === emoji}
                      onclick={() => selectedIcon = emoji}
                      aria-pressed={selectedIcon === emoji}
                    >
                      {emoji}
                    </button>
                  {/each}
                </div>
              </div>

              <div class="form-group">
                <label for="workspace-dir">Working Directory</label>
                <div class="dir-input-group">
                  <input id="workspace-dir" type="text" bind:value={workingDir} placeholder="./" />
                  <button class="btn-browse" onclick={browseDirectory} title="Browse..." aria-label="Browse for directory">📁</button>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label for="workspace-columns">Columns</label>
                  <input id="workspace-columns" type="number" min="1" max="8" bind:value={columns} />
                </div>
                <div class="form-group">
                  <label for="workspace-rows">Rows</label>
                  <input id="workspace-rows" type="number" min="1" max="8" bind:value={rows} />
                </div>
              </div>
            </div>
            
            <!-- Right: Agent Assignment -->
            <div class="agents-panel">
              <div class="agents-header">
                <h4>Agent Assignment</h4>
                <div class="agent-actions">
                  <button class="btn-auto" onclick={handleAutoDistribute}>Auto</button>
                  <button class="btn-clear" onclick={clearAllAgents}>Clear</button>
                </div>
              </div>
              
              <!-- Slots Grid -->
              <div class="slots-grid" style="--cols: {Math.min(columns, 4)}; --rows: {Math.ceil(slotAssignments.length / Math.min(columns, 4))};">
                {#each slotAssignments as agent, i}
                  <div
                    class="slot"
                    class:assigned={agent !== null}
                    onclick={() => handleSlotClick(i)}
                    ondragover={(e) => e.preventDefault()}
                    ondrop={(e) => handleDropOnSlot(e, i)}
                    role="button"
                    tabindex="0"
                    onkeydown={(e) => e.key === 'Enter' && handleSlotClick(i)}
                    title={agent ? AGENT_CONFIGS.find(a => a.type === agent)?.name : `Slot ${i + 1} (click to clear)`}
                  >
                    <span class="slot-number">{i + 1}</span>
                    {#if agent}
                      {@const agentInfo = AGENT_CONFIGS.find(a => a.type === agent)}
                      <span class="slot-agent">{agentInfo?.icon}</span>
                    {:else}
                      <span class="slot-placeholder">+</span>
                    {/if}
                  </div>
                {/each}
              </div>
              
              <!-- Agent Palette -->
              <div class="agent-palette">
                <p class="hint">Drag agents to slots or use +/- buttons:</p>
                <div class="agent-list">
                  {#each AGENT_CONFIGS as { type, name, icon }}
                    <AgentItem
                      {type}
                      {name}
                      {icon}
                      count={getAgentCount(type)}
                      max={columns * rows}
                      onIncrement={() => incrementAgent(type)}
                      onDecrement={() => decrementAgent(type)}
                      onDragStart={handleDragStart}
                    />
                  {/each}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn-back" onclick={goBack}>← Back</button>
          <button class="btn-create" onclick={handleCreateWorkspace} disabled={!workspaceName.trim()}>
            {editingWorkspace ? 'Save Changes' : 'Create Workspace'}
          </button>
        </div>
      {/if}
    </div>
  </div>
{/if}

<style>
  .modal-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
  }

  .creation-modal {
    background: var(--color-bg-surface0, #1e1e2e);
    border-radius: 12px;
    width: 800px;
    max-width: 90vw;
    max-height: 85vh;
    display: flex;
    flex-direction: column;
    border: 1px solid var(--color-border, #45475a);
    overflow: hidden;
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 16px 20px;
    border-bottom: 1px solid var(--color-border, #45475a);
  }

  .modal-header h3 {
    margin: 0;
    color: var(--color-text, #cdd6f4);
    font-size: 18px;
  }

  .close-btn {
    background: none;
    border: none;
    color: var(--color-text-subtext0, #6c7086);
    font-size: 24px;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 4px;
    transition: all 0.15s ease;
  }

  .close-btn:hover {
    color: var(--color-text, #cdd6f4);
    background: var(--color-bg-surface1, #313244);
  }

  .step-content {
    padding: 20px;
    overflow-y: auto;
    flex: 1;
    min-height: 0;
  }

  .step-description {
    color: var(--color-text-subtext0, #a6adc8);
    margin: 0 0 16px;
    font-size: 14px;
  }

  /* Template Grid */
  .template-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 12px;
  }

  .template-card {
    background: var(--color-bg-surface1, #313244);
    border: 2px solid var(--color-border, #45475a);
    border-radius: 8px;
    padding: 16px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .template-card:hover {
    background: var(--color-bg-surface2, #41435a);
    border-color: var(--color-border-hover, #585b70);
  }

  .template-card.selected {
    border-color: var(--color-primary, #89b4fa);
    background: rgba(137, 180, 250, 0.1);
  }

  .template-icon {
    font-size: 32px;
  }

  .template-name {
    color: var(--color-text, #cdd6f4);
    font-weight: 500;
  }

  .template-layout {
    color: var(--color-text-subtext0, #6c7086);
    font-size: 12px;
  }

  /* Configure Step */
  .configure-step {
    padding: 16px;
  }

  .configure-layout {
    display: grid;
    grid-template-columns: 280px 1fr;
    gap: 20px;
    height: 100%;
  }

  .settings-panel {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .form-group label,
  .form-group .field-label {
    color: var(--color-text, #cdd6f4);
    font-size: 12px;
    font-weight: 500;
  }

  .form-group input {
    background: var(--color-bg-base, #1e1e2e);
    border: 1px solid var(--color-border, #45475a);
    color: var(--color-text, #cdd6f4);
    padding: 8px 10px;
    border-radius: 6px;
    font-size: 13px;
    outline: none;
    transition: all 0.15s ease;
  }

  .form-group input:focus {
    border-color: var(--color-primary, #89b4fa);
  }

  .hint {
    color: var(--color-text-subtext0, #6c7086);
    font-size: 11px;
    margin: 0;
  }

  .dir-input-group {
    display: flex;
    gap: 6px;
  }

  .dir-input-group input {
    flex: 1;
  }

  .btn-browse {
    padding: 6px 10px;
    background: var(--color-bg-surface1, #313244);
    border: 1px solid var(--color-border, #45475a);
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.15s ease;
  }

  .btn-browse:hover {
    background: var(--color-bg-surface2, #41435a);
  }

  .icon-grid {
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    gap: 6px;
  }

  .icon-btn {
    background: var(--color-bg-base, #1e1e2e);
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 6px;
    font-size: 18px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .icon-btn:hover {
    background: var(--color-bg-surface1, #313244);
  }

  .icon-btn.selected {
    border-color: var(--color-primary, #89b4fa);
    background: rgba(137, 180, 250, 0.1);
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
  }

  /* Agents Panel */
  .agents-panel {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-height: 0;
  }

  .agents-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .agents-header h4 {
    margin: 0;
    color: var(--color-text, #cdd6f4);
    font-size: 14px;
  }

  .agent-actions {
    display: flex;
    gap: 6px;
  }

  .btn-auto,
  .btn-clear {
    padding: 4px 10px;
    border-radius: 4px;
    border: none;
    cursor: pointer;
    font-size: 11px;
    font-weight: 500;
    transition: all 0.15s ease;
  }

  .btn-auto {
    background: var(--color-primary, #89b4fa);
    color: var(--color-bg-base, #1e1e2e);
  }

  .btn-clear {
    background: var(--color-bg-surface1, #313244);
    color: var(--color-text, #cdd6f4);
  }

  .btn-auto:hover {
    background: var(--color-primary-hover, #74a9f0);
  }

  .btn-clear:hover {
    background: var(--color-error, #f38ba8);
    color: var(--color-bg-base, #1e1e2e);
  }

  /* Slots Grid */
  .slots-grid {
    display: grid;
    grid-template-columns: repeat(var(--cols, 2), 1fr);
    grid-template-rows: repeat(var(--rows, 2), 1fr);
    gap: 6px;
    padding: 10px;
    background: var(--color-bg-base, #1e1e2e);
    border-radius: 8px;
    border: 1px solid var(--color-border, #45475a);
    min-height: 120px;
  }

  .slot {
    background: var(--color-bg-surface1, #313244);
    border: 2px dashed var(--color-border, #45475a);
    border-radius: 6px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.15s ease;
    position: relative;
    min-height: 40px;
    aspect-ratio: 1;
  }

  .slot:hover {
    border-color: var(--color-border-hover, #585b70);
    background: var(--color-bg-surface2, #41435a);
  }

  .slot.assigned {
    border-style: solid;
    border-color: var(--color-primary, #89b4fa);
    background: rgba(137, 180, 250, 0.1);
  }

  .slot-number {
    position: absolute;
    top: 2px;
    left: 4px;
    font-size: 9px;
    color: var(--color-text-subtext0, #6c7086);
    font-weight: 600;
  }

  .slot-agent {
    font-size: 18px;
  }

  .slot-placeholder {
    font-size: 16px;
    color: var(--color-text-subtext0, #6c7086);
  }

  /* Agent Palette */
  .agent-palette {
    margin-top: auto;
  }

  .agent-list {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 6px;
    max-height: 120px;
    overflow-y: auto;
  }


  /* Footer */
  .modal-footer {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    padding: 16px 20px;
    border-top: 1px solid var(--color-border, #45475a);
    background: var(--color-bg-mantle, #181825);
  }

  .btn-back,
  .btn-create {
    padding: 10px 20px;
    border-radius: 6px;
    border: none;
    cursor: pointer;
    font-size: 14px;
    font-weight: 500;
    transition: all 0.15s ease;
  }

  .btn-back {
    background: var(--color-bg-surface1, #313244);
    color: var(--color-text, #cdd6f4);
  }

  .btn-create {
    background: var(--color-primary, #89b4fa);
    color: var(--color-bg-base, #1e1e2e);
    margin-left: auto;
  }

  .btn-back:hover {
    background: var(--color-bg-surface2, #41435a);
  }

  .btn-create:hover {
    background: var(--color-primary-hover, #74a9f0);
  }

  .btn-create:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>

// src/components/workspaces/WorkspaceCreationModal.tsx
import React, { useState, useEffect } from 'react';
import { useWorkspaceStore } from '../../stores/workspaceStore';
import { useTemplateStore } from '../../stores/templateStore';
import { AgentConfig, AgentType, AgentAllocation, Template, WorkspaceLayout } from '../../types/workspace';
import { AgentAllocationSlider } from '../agents/AgentAllocationSlider';
import { TemplateSelector } from '../agents/TemplateSelector';

// Import generateId from workspaceStore to avoid duplication
const generateId = () => Math.random().toString(36).substring(2, 9);

interface WorkspaceCreationModalProps {
  isOpen: boolean;
  onClose: () => void;
  editingWorkspace?: WorkspaceLayout | null;
}

const agentTypeInfo: { type: AgentType; label: string; description: string; icon: string; color: string }[] = [
  { type: 'claude-code', label: 'Claude Code', description: "Anthropic's CLI agent", icon: '🤖', color: '#a6adc8' },
  { type: 'opencode', label: 'OpenCode', description: 'Open source coding agent', icon: '🔓', color: '#a6adc8' },
  { type: 'droid', label: 'Droid', description: 'Custom AI agent', icon: '🤖', color: '#a6adc8' },
  { type: 'gemini-cli', label: 'Gemini CLI', description: "Google's AI agent", icon: '✨', color: '#89b4fa' },
  { type: 'cursor', label: 'Cursor CLI', description: 'AI-powered coding', icon: '🎯', color: '#f38ba8' },
  { type: 'codex', label: 'Codex CLI', description: "OpenAI's coding agent", icon: '🧠', color: '#a6e3a1' },
  { type: 'oh-my-pi', label: 'Oh My Pi', description: 'Minimalist agent', icon: '🥧', color: '#fab387' },
  { type: 'aider', label: 'Aider', description: 'Git-native AI pair', icon: '🚀', color: '#cba6f7' },
  { type: 'goose', label: 'Goose', description: 'Extensible AI agent', icon: '🪿', color: '#94e2d5' },
  { type: 'warp', label: 'Warp AI', description: 'Terminal with AI', icon: '⚡', color: '#f9e2af' },
  { type: 'amp', label: 'Amp', description: 'Code quality agent', icon: '🔥', color: '#eba0ac' },
  { type: 'kiro', label: 'Kiro', description: 'AWS coding agent', icon: '☁️', color: '#89dceb' },
];

const emojis = ['💼', '🚀', '💻', '🔧', '⚡', '🎯', '📦', '🛠️', '📊', '🎨'];

// Helper function to extract agent allocation from existing workspace
const extractAgentAllocation = (
  terminals: WorkspaceLayout['terminals']
): AgentAllocation => {
  const allocation: AgentAllocation = {
    claudeCode: 0,
    opencode: 0,
    droid: 0,
    geminiCli: 0,
    cursor: 0,
    codex: 0,
    ohMyPi: 0,
    aider: 0,
    goose: 0,
    warp: 0,
    amp: 0,
    kiro: 0,
  };

  terminals.forEach(term => {
    if (term.agent) {
      switch (term.agent.type) {
        case 'claude-code': allocation.claudeCode++; break;
        case 'opencode': allocation.opencode++; break;
        case 'droid': allocation.droid++; break;
        case 'gemini-cli': allocation.geminiCli++; break;
        case 'cursor': allocation.cursor++; break;
        case 'codex': allocation.codex++; break;
        case 'oh-my-pi': allocation.ohMyPi++; break;
        case 'aider': allocation.aider++; break;
        case 'goose': allocation.goose++; break;
        case 'warp': allocation.warp++; break;
        case 'amp': allocation.amp++; break;
        case 'kiro': allocation.kiro++; break;
      }
    }
  });

  return allocation;
};

// Helper function to generate agent assignments from allocation
const generateAgentAssignments = (
  allocation: AgentAllocation,
  total: number
): Record<string, AgentConfig> => {
  const assignments: Record<string, AgentConfig> = {};
  let terminalIndex = 0;

  // Allocate agents in order of priority
  const agentAllocations = [
    { type: 'claude-code' as const, count: allocation.claudeCode },
    { type: 'opencode' as const, count: allocation.opencode },
    { type: 'droid' as const, count: allocation.droid },
    { type: 'gemini-cli' as const, count: allocation.geminiCli },
    { type: 'cursor' as const, count: allocation.cursor },
    { type: 'codex' as const, count: allocation.codex },
    { type: 'oh-my-pi' as const, count: allocation.ohMyPi },
    { type: 'aider' as const, count: allocation.aider },
    { type: 'goose' as const, count: allocation.goose },
    { type: 'warp' as const, count: allocation.warp },
    { type: 'amp' as const, count: allocation.amp },
    { type: 'kiro' as const, count: allocation.kiro },
  ];

  // Allocate each agent type
  for (const agent of agentAllocations) {
    for (let i = 0; i < agent.count; i++) {
      assignments[`terminal-${terminalIndex++}`] = { type: agent.type, enabled: true };
    }
  }

  // Rest are None
  while (terminalIndex < total) {
    assignments[`terminal-${terminalIndex++}`] = { type: 'none', enabled: false };
  }

  return assignments;
};

export const WorkspaceCreationModal: React.FC<WorkspaceCreationModalProps> = ({ isOpen, onClose }) => {
  const { addWorkspace, setCurrentWorkspace, updateWorkspace, editingWorkspace } = useWorkspaceStore();
  const { loadTemplates } = useTemplateStore();

  const isEditMode = !!editingWorkspace;

  // Step 1: Template Selection
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);

  // Step 2: Basic Info
  const [workspaceName, setWorkspaceName] = useState('My Workspace');
  const [selectedIcon, setSelectedIcon] = useState(emojis[0]);

  // Step 3: Working Directory
  const [workingDir, setWorkingDir] = useState('./');

  // Step 4: Agent Allocation
  const [agentAllocation, setAgentAllocation] = useState<AgentAllocation>({
    claudeCode: 0,
    opencode: 0,
    droid: 0,
    geminiCli: 0,
    cursor: 0,
    codex: 0,
    ohMyPi: 0,
    aider: 0,
    goose: 0,
    warp: 0,
    amp: 0,
    kiro: 0,
  });

  // Derived state from template
  const totalTerminals = selectedTemplate ? selectedTemplate.columns * selectedTemplate.rows : 0;
  const allocatedCount = agentAllocation.claudeCode + agentAllocation.opencode + agentAllocation.droid + 
                          agentAllocation.geminiCli + agentAllocation.cursor + agentAllocation.codex + 
                          agentAllocation.ohMyPi + agentAllocation.aider + agentAllocation.goose + 
                          agentAllocation.warp + agentAllocation.amp + agentAllocation.kiro;
  const noneCount = totalTerminals - allocatedCount;

  // Generate agentAssignments from allocation
  const [agentAssignments, setAgentAssignments] = useState<Record<string, AgentConfig>>({});

  useEffect(() => {
    if (isOpen) {
      loadTemplates();
    }
  }, [isOpen, loadTemplates]);

  // Load workspace data when editing
  useEffect(() => {
    if (isEditMode && editingWorkspace && isOpen) {
      // Preload workspace data into form
      setWorkspaceName(editingWorkspace.name);
      setSelectedIcon(editingWorkspace.icon || emojis[0]);
      setWorkingDir(editingWorkspace.terminals[0]?.cwd || './');
      
      // Extract agent allocation from existing terminals
      const allocation = extractAgentAllocation(editingWorkspace.terminals);
      setAgentAllocation(allocation);

      // Find matching template
      loadTemplates();
      const { getTemplate } = useTemplateStore.getState();
      const template = getTemplateByLayout(editingWorkspace.columns, editingWorkspace.rows);
      if (template) {
        setSelectedTemplate(template);
      }
    } else if (!isEditMode) {
      // Reset form for create mode
      resetForm();
    }
  }, [editingWorkspace, isEditMode, isOpen]);

  useEffect(() => {
    if (totalTerminals > 0) {
      const assignments = generateAgentAssignments(agentAllocation, totalTerminals);
      setAgentAssignments(assignments);
    }
  }, [agentAllocation, totalTerminals]);

  // Reset allocation when template changes if it exceeds new total
  useEffect(() => {
    if (allocatedCount > totalTerminals && totalTerminals > 0) {
      setAgentAllocation({
        claudeCode: 0,
        opencode: 0,
        droid: 0,
        geminiCli: 0,
        cursor: 0,
        codex: 0,
        ohMyPi: 0,
        aider: 0,
        goose: 0,
        warp: 0,
        amp: 0,
        kiro: 0,
      });
    }
  }, [totalTerminals]);

// Helper function to find template by layout
const getTemplateByLayout = (columns: number, rows: number): Template | null => {
  const { getTemplate } = useTemplateStore.getState();
  
  // Try to find exact match
  const templates = [
    getTemplate('single'),      // 1x1
    getTemplate('dual'),        // 2x1
    getTemplate('quad'),        // 2x2
    getTemplate('six'),         // 3x2
    getTemplate('eight'),       // 4x2
    getTemplate('ten'),         // 5x2
    getTemplate('twelve'),      // 4x3
    getTemplate('fourteen'),    // custom
    getTemplate('sixteen'),     // 4x4
  ].filter(Boolean) as Template[];

  return templates.find(t => t.columns === columns && t.rows === rows) || null;
};

// Initialize with single template when modal opens
useEffect(() => {
  if (isOpen && !selectedTemplate && !isEditMode) {
    // Default to "single" template - will be loaded asynchronously
    const initTemplates = async () => {
      await loadTemplates();
      const { getTemplate } = useTemplateStore.getState();
      const singleTemplate = getTemplate('single');
      if (singleTemplate) {
        setSelectedTemplate(singleTemplate);
      }
    };
    initTemplates();
  }
}, [isOpen, isEditMode]);

  const handleBrowseFolder = async () => {
    if (window.electronAPI) {
      const result = await window.electronAPI.showOpenDialog({
        properties: ['openDirectory', 'createDirectory'],
        title: 'Select Working Directory',
      });

      if (!result.canceled && result.filePaths.length > 0) {
        setWorkingDir(result.filePaths[0]);
      }
    } else {
      const folder = prompt('Enter working directory path:', workingDir);
      if (folder) {
        setWorkingDir(folder);
      }
    }
  };

  const handleReset = () => {
    setAgentAllocation({
      claudeCode: 0,
      opencode: 0,
      droid: 0,
      geminiCli: 0,
      cursor: 0,
      codex: 0,
      ohMyPi: 0,
      aider: 0,
      goose: 0,
      warp: 0,
      amp: 0,
      kiro: 0,
    });
  };

  const handleAutoDistribute = () => {
    if (totalTerminals === 0) return;

    // Auto-fill by priority: distribute evenly among top agents
    const numAgents = 12; // Total number of agent types
    const base = Math.floor(totalTerminals / numAgents);
    const remainder = totalTerminals % numAgents;

    const allocation = {
      claudeCode: base,
      opencode: base,
      droid: base,
      geminiCli: base,
      cursor: base,
      codex: base,
      ohMyPi: base,
      aider: base,
      goose: base,
      warp: base,
      amp: base,
      kiro: base,
    };

    // Distribute remainder
    const keys = Object.keys(allocation) as (keyof typeof allocation)[];
    for (let i = 0; i < remainder; i++) {
      allocation[keys[i]]++;
    }

    setAgentAllocation(allocation);
  };

  const handleCreateWorkspace = () => {
    if (!selectedTemplate) {
      alert('Please select a template');
      return;
    }

    const finalAgentAssignments: Record<string, AgentConfig> = {};
    Object.entries(agentAssignments).forEach(([key, config], index) => {
      finalAgentAssignments[`term-${index}`] = config;
    });

    if (isEditMode && editingWorkspace) {
      // Edit mode: recreate workspace with new layout
      const getShell = () => editingWorkspace.terminals[0]?.shell || 'powershell.exe';
      
      const newTerminals = [];
      const totalNewTerminals = selectedTemplate.columns * selectedTemplate.rows;
      
      // Preserve agent allocation based on the slider values
      let terminalIndex = 0;
      
      // Helper to allocate terminals for an agent type
      const allocateAgent = (type: AgentType, count: number) => {
        for (let i = 0; i < count && terminalIndex < totalNewTerminals; i++) {
          newTerminals.push({
            id: generateId(),
            title: `Terminal ${terminalIndex + 1}`,
            cwd: workingDir,
            shell: getShell(),
            status: 'stopped' as const,
            agent: { type, enabled: true },
          });
          terminalIndex++;
        }
      };
      
      // Allocate agents based on current allocation
      allocateAgent('claude-code', agentAllocation.claudeCode);
      allocateAgent('opencode', agentAllocation.opencode);
      allocateAgent('droid', agentAllocation.droid);
      allocateAgent('gemini-cli', agentAllocation.geminiCli);
      allocateAgent('cursor', agentAllocation.cursor);
      allocateAgent('codex', agentAllocation.codex);
      allocateAgent('oh-my-pi', agentAllocation.ohMyPi);
      allocateAgent('aider', agentAllocation.aider);
      allocateAgent('goose', agentAllocation.goose);
      allocateAgent('warp', agentAllocation.warp);
      allocateAgent('amp', agentAllocation.amp);
      allocateAgent('kiro', agentAllocation.kiro);
      
      // Fill remaining with none
      while (terminalIndex < totalNewTerminals) {
        newTerminals.push({
          id: generateId(),
          title: `Terminal ${terminalIndex + 1}`,
          cwd: workingDir,
          shell: getShell(),
          status: 'stopped' as const,
          agent: { type: 'none' as const, enabled: false },
        });
        terminalIndex++;
      }

      // Update workspace with new layout and terminals
      updateWorkspace(editingWorkspace.id, {
        name: workspaceName,
        icon: selectedIcon,
        columns: selectedTemplate.columns,
        rows: selectedTemplate.rows,
        terminals: newTerminals,
      });
    } else {
      // Create mode: add new workspace
      const workspace = addWorkspace({
        name: workspaceName,
        columns: selectedTemplate.columns,
        rows: selectedTemplate.rows,
        cwd: workingDir,
        icon: selectedIcon,
        agentAssignments: finalAgentAssignments,
        templateId: selectedTemplate.id,
      });

      setCurrentWorkspace(workspace);
    }
    
    onClose();
    resetForm();
  };

  const resetForm = () => {
    setWorkspaceName('My Workspace');
    setSelectedIcon(emojis[0]);
    setSelectedTemplate(null);
    setWorkingDir('./');
    setAgentAllocation({
      claudeCode: 0,
      opencode: 0,
      droid: 0,
      geminiCli: 0,
      cursor: 0,
      codex: 0,
      ohMyPi: 0,
      aider: 0,
      goose: 0,
      warp: 0,
      amp: 0,
      kiro: 0,
    });
  };

  // Calculate max values for each slider
  const getMaxForAgent = (excludeKey: keyof AgentAllocation) => {
    const sumOthers = Object.entries(agentAllocation)
      .filter(([key]) => key !== excludeKey)
      .reduce((sum, [, value]) => sum + value, 0);
    return totalTerminals - sumOthers;
  };

  if (!isOpen) return null;

  return (
    <div style={styles.overlay}>
      <div style={styles.modal}>
        {/* Header */}
        <div style={styles.header}>
          <h2 style={styles.title}>{isEditMode ? 'Edit Workspace' : 'Create New Workspace'}</h2>
          <button onClick={onClose} style={styles.closeButton}>×</button>
        </div>

        {/* Content */}
        <div style={styles.content}>
          {/* Step 1: Template Selection */}
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>1. Select Template</h3>
            <p style={styles.sectionDescription}>
              Choose a pre-built template or create a custom one
            </p>
            <TemplateSelector
              selectedTemplate={selectedTemplate}
              onSelectTemplate={setSelectedTemplate}
            />
          </div>

          {/* Step 2: Basic Info */}
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>2. Basic Information</h3>
            <div style={styles.formGroup}>
              <label style={styles.label}>Workspace Name</label>
              <input
                type="text"
                value={workspaceName}
                onChange={(e) => setWorkspaceName(e.target.value)}
                style={styles.input}
                placeholder="Enter workspace name"
              />
            </div>
            <div style={styles.formGroup}>
              <label style={styles.label}>Icon</label>
              <div style={styles.emojiPicker}>
                {emojis.map((emoji) => (
                  <button
                    key={emoji}
                    onClick={() => setSelectedIcon(emoji)}
                    style={{
                      ...styles.emojiButton,
                      backgroundColor: selectedIcon === emoji ? '#45475a' : 'transparent',
                      border: selectedIcon === emoji ? '2px solid #89b4fa' : '1px solid #45475a',
                    }}
                  >
                    {emoji}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Step 3: Working Directory */}
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>3. Working Directory</h3>
            <div style={styles.formGroup}>
              <label style={styles.label}>Terminal Working Directory</label>
              <div style={styles.folderInput}>
                <input
                  type="text"
                  value={workingDir}
                  onChange={(e) => setWorkingDir(e.target.value)}
                  style={{ ...styles.input, flex: 1 }}
                  placeholder="e.g., C:\Projects\my-app"
                />
                <button onClick={handleBrowseFolder} style={styles.browseButton}>
                  📁 Browse
                </button>
              </div>
            </div>
          </div>

          {/* Step 4: Agent Allocation */}
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>4. AI Agents Allocation</h3>
            <p style={styles.sectionDescription}>
              Drag sliders to allocate AI agents to terminals
            </p>

            {/* Allocation Summary */}
            <div style={styles.allocationSummary}>
              <div style={styles.summaryRow}>
                <span style={styles.summaryLabel}>Total Terminals:</span>
                <span style={styles.summaryValue}>{totalTerminals}</span>
              </div>
              <div style={styles.summaryRow}>
                <span style={styles.summaryLabel}>Allocated:</span>
                <span style={{
                  ...styles.summaryValue,
                  color: allocatedCount > totalTerminals ? '#f38ba8' : '#a6e3a1'
                }}>
                  {allocatedCount}/{totalTerminals}
                </span>
              </div>
              {noneCount > 0 && (
                <div style={styles.summaryRow}>
                  <span style={{ ...styles.summaryLabel, color: '#6c7086' }}>None (plain terminals):</span>
                  <span style={{ ...styles.summaryValue, color: '#6c7086' }}>{noneCount}</span>
                </div>
              )}
            </div>

            {/* Agent Sliders */}
            <div style={styles.slidersContainer}>
              {agentTypeInfo.map((agent) => {
                const allocationKey = agent.type === 'claude-code' ? 'claudeCode' : 
                                     agent.type === 'opencode' ? 'opencode' :
                                     agent.type === 'gemini-cli' ? 'geminiCli' :
                                     agent.type === 'cursor' ? 'cursor' :
                                     agent.type === 'codex' ? 'codex' :
                                     agent.type === 'oh-my-pi' ? 'ohMyPi' :
                                     agent.type === 'aider' ? 'aider' :
                                     agent.type === 'goose' ? 'goose' :
                                     agent.type === 'warp' ? 'warp' :
                                     agent.type === 'amp' ? 'amp' :
                                     agent.type === 'kiro' ? 'kiro' : 'droid';
                
                return (
                  <AgentAllocationSlider
                    key={agent.type}
                    label={agent.label}
                    icon={agent.icon}
                    value={agentAllocation[allocationKey]}
                    maxValue={getMaxForAgent(allocationKey)}
                    onChange={(value) => setAgentAllocation(prev => ({
                      ...prev,
                      [allocationKey]: value
                    }))}
                    color={agent.color}
                    description={agent.description}
                  />
                );
              })}
            </div>

            {/* Action Buttons */}
            <div style={styles.allocationActions}>
              <button onClick={handleReset} style={styles.resetButton}>
                🔄 Reset to None
              </button>
              <button onClick={handleAutoDistribute} style={styles.autoButton}>
                ⚡ Auto-distribute
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={styles.footer}>
          <button onClick={onClose} style={styles.cancelButton}>
            Cancel
          </button>
          <button
            onClick={handleCreateWorkspace}
            style={{
              ...styles.createButton,
              opacity: selectedTemplate ? 1 : 0.5,
              pointerEvents: selectedTemplate ? 'auto' : 'none',
            }}
          >
            {isEditMode ? '💾 Save Changes' : '🚀 Create Workspace'}
          </button>
        </div>
      </div>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: '#1e1e2e',
    borderRadius: '12px',
    border: '1px solid #45475a',
    width: '90%',
    maxWidth: '900px',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: '1px solid #45475a',
  },
  title: {
    fontSize: '20px',
    fontWeight: 600,
    color: '#cdd6f4',
    margin: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    color: '#a6adc8',
    fontSize: '28px',
    cursor: 'pointer',
    padding: '0 8px',
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px',
  },
  section: {
    marginBottom: '32px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#89b4fa',
    marginBottom: '16px',
  },
  sectionDescription: {
    fontSize: '13px',
    color: '#a6adc8',
    marginBottom: '12px',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 500,
    color: '#bac2de',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    fontSize: '14px',
    backgroundColor: '#313244',
    border: '1px solid #45475a',
    borderRadius: '6px',
    color: '#cdd6f4',
    outline: 'none',
  },
  emojiPicker: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  emojiButton: {
    fontSize: '24px',
    padding: '8px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  folderInput: {
    display: 'flex',
    gap: '8px',
  },
  browseButton: {
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 600,
    backgroundColor: '#45475a',
    color: '#cdd6f4',
    border: '1px solid #585b70',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  allocationSummary: {
    backgroundColor: '#313244',
    border: '1px solid #45475a',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '20px',
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  summaryLabel: {
    fontSize: '14px',
    color: '#bac2de',
  },
  summaryValue: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#cdd6f4',
    backgroundColor: '#45475a',
    padding: '4px 12px',
    borderRadius: '4px',
  },
  slidersContainer: {
    marginBottom: '16px',
  },
  allocationActions: {
    display: 'flex',
    gap: '12px',
  },
  resetButton: {
    flex: 1,
    padding: '10px 16px',
    fontSize: '13px',
    fontWeight: 600,
    backgroundColor: '#313244',
    color: '#a6adc8',
    border: '1px solid #45475a',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  autoButton: {
    flex: 1,
    padding: '10px 16px',
    fontSize: '13px',
    fontWeight: 600,
    backgroundColor: '#45475a',
    color: '#89b4fa',
    border: '1px solid #585b70',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    padding: '20px 24px',
    borderTop: '1px solid #45475a',
  },
  cancelButton: {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: 600,
    backgroundColor: 'transparent',
    color: '#a6adc8',
    border: '1px solid #45475a',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  createButton: {
    padding: '10px 24px',
    fontSize: '14px',
    fontWeight: 600,
    backgroundColor: '#89b4fa',
    color: '#1e1e2e',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
};
