// src/App.tsx
import React, { useEffect, useState } from 'react';
import { TitleBar } from './components/TitleBar';
import { TerminalGrid } from './components/TerminalGrid';
import { WorkspaceTabBar } from './components/WorkspaceTabBar';
import { WorkspaceSwitcherModal } from './components/WorkspaceSwitcherModal';
import { SettingsModal } from './components/SettingsModal';
import { useWorkspaceStore } from './stores/workspaceStore';
import { getAppVersion } from './utils/version';

function App() {
  const theme = useWorkspaceStore((state) => state.theme);
  const workspace = useWorkspaceStore((state) => state.currentWorkspace);
  const loadWorkspaces = useWorkspaceStore((state) => state.loadWorkspaces);
  const setWorkspaceModalOpen = useWorkspaceStore((state) => state.setWorkspaceModalOpen);
  const setCurrentWorkspace = useWorkspaceStore((state) => state.setCurrentWorkspace);
  const setActiveTerminal = useWorkspaceStore((state) => state.setActiveTerminal);
  const getNextWorkspace = useWorkspaceStore((state) => state.getNextWorkspace);
  const getPreviousWorkspace = useWorkspaceStore((state) => state.getPreviousWorkspace);
  const getNextTerminal = useWorkspaceStore((state) => state.getNextTerminal);
  const getPreviousTerminal = useWorkspaceStore((state) => state.getPreviousTerminal);
  const getWorkspaceByIndex = useWorkspaceStore((state) => state.getWorkspaceByIndex);
  const getTerminalByIndex = useWorkspaceStore((state) => state.getTerminalByIndex);
  const workspaces = useWorkspaceStore((state) => state.workspaces);
  const activeTerminalId = useWorkspaceStore((state) => state.activeTerminalId);

  // Workspace switcher modal state
  const [workspaceSwitcherOpen, setWorkspaceSwitcherOpen] = useState(false);
  const [settingsModalOpen, setSettingsModalOpen] = useState(false);
  const [appVersion, setAppVersion] = useState<string>('');

  // Load app version
  useEffect(() => {
    getAppVersion().then(setAppVersion);
  }, []);

  // Load workspaces from electron-store on mount (only once)
  useEffect(() => {
    console.log('[App] Loading workspaces on mount...');
    loadWorkspaces();
  }, []);

  // Listen for workspace switcher open event from TerminalCell
  useEffect(() => {
    const handleOpenWorkspaceSwitcher = () => {
      console.log('[App] Received open-workspace-switcher event from TerminalCell');
      setWorkspaceSwitcherOpen(true);
    };

    window.addEventListener('open-workspace-switcher', handleOpenWorkspaceSwitcher);
    return () => window.removeEventListener('open-workspace-switcher', handleOpenWorkspaceSwitcher);
  }, []);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't trigger shortcuts when typing in input fields
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
        return;
      }

      // Ctrl+, (comma): Open Settings
      if (e.ctrlKey && e.key === ',') {
        e.preventDefault();
        setSettingsModalOpen(true);
        return;
      }

      // Ctrl+Shift+N: New workspace
      if (e.ctrlKey && e.shiftKey && e.key === 'N') {
        e.preventDefault();
        setWorkspaceModalOpen(true);
        return;
      }

      // Ctrl+Tab: Cycle to next workspace with modal preview
      if (e.ctrlKey && e.key === 'Tab') {
        e.preventDefault();

        // Always cycle to next workspace when Ctrl+Tab is pressed
        const nextWs = getNextWorkspace();
        console.log('[App] Ctrl+Tab pressed, cycling to next workspace:', nextWs?.name);
        if (nextWs) {
          setCurrentWorkspace(nextWs);
        }

        // Open modal to show preview
        setWorkspaceSwitcherOpen(true);
        return;
      }

      // Ctrl+Shift+Tab: Previous workspace
      if (e.ctrlKey && e.shiftKey && e.key === 'Tab') {
        e.preventDefault();
        const prevWorkspace = getPreviousWorkspace();
        console.log('[App] Ctrl+Shift+Tab pressed, cycling to previous workspace:', prevWorkspace?.name);
        if (prevWorkspace) {
          setCurrentWorkspace(prevWorkspace);
        }
        setWorkspaceSwitcherOpen(true);
        return;
      }

      // Ctrl+PageUp: Previous workspace
      if (e.ctrlKey && e.key === 'PageUp') {
        e.preventDefault();
        const prevWorkspace = getPreviousWorkspace();
        console.log('[App] Ctrl+PageUp pressed, switching to:', prevWorkspace?.name);
        if (prevWorkspace) {
          setCurrentWorkspace(prevWorkspace);
        }
        return;
      }

      // Ctrl+PageDown: Next workspace
      if (e.ctrlKey && e.key === 'PageDown') {
        e.preventDefault();
        const nextWorkspace = getNextWorkspace();
        console.log('[App] Ctrl+PageDown pressed, switching to:', nextWorkspace?.name);
        if (nextWorkspace) {
          setCurrentWorkspace(nextWorkspace);
        }
        return;
      }

      // Ctrl+T: Next terminal (or terminal at index with number)
      if (e.ctrlKey && e.key === 't') {
        e.preventDefault();

        // Check if a number key is pressed (Ctrl+1 through Ctrl+9)
        const numKey = e.code.match(/Digit(\d)/);
        if (numKey) {
          const index = parseInt(numKey[1]) - 1;
          const terminal = getTerminalByIndex(index);
          if (terminal) {
            setActiveTerminal(terminal.id);
          }
        } else {
          const nextTerminal = getNextTerminal();
          if (nextTerminal) {
            setActiveTerminal(nextTerminal.id);
          }
        }
        return;
      }

      // Ctrl+Shift+T: Previous terminal
      if (e.ctrlKey && e.shiftKey && e.key === 'T') {
        e.preventDefault();
        const prevTerminal = getPreviousTerminal();
        if (prevTerminal) {
          setActiveTerminal(prevTerminal.id);
        }
        return;
      }

      // Alt+1 through Alt+9: Switch to workspace by index
      if (e.altKey && e.key.match(/^[1-9]$/)) {
        e.preventDefault();
        const index = parseInt(e.key) - 1;
        const ws = getWorkspaceByIndex(index);
        if (ws) {
          setCurrentWorkspace(ws);
        }
        return;
      }
    };

    const handleKeyUp = (e: KeyboardEvent) => {
      if (e.key === 'Control') {
        // Close workspace switcher when Ctrl is released
        if (workspaceSwitcherOpen) {
          console.log('[App] Ctrl released, closing modal');
          setWorkspaceSwitcherOpen(false);
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    };
  }, [
    workspaceSwitcherOpen,
    getNextWorkspace,
    getPreviousWorkspace,
    getNextTerminal,
    getPreviousTerminal,
    getWorkspaceByIndex,
    getTerminalByIndex,
    setCurrentWorkspace,
    setActiveTerminal,
    setWorkspaceModalOpen
  ]);

  const handleSelectWorkspace = (workspaceId: string) => {
    console.log('[App] handleSelectWorkspace called with:', workspaceId);
    const ws = workspaces.find(w => w.id === workspaceId);
    if (ws) {
      setCurrentWorkspace(ws);
      console.log('[App] Switched to workspace:', ws.name);
    }
    setWorkspaceSwitcherOpen(false);
  };

  return (
    <div
      className="app-container"
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: theme === 'dark' ? '#1e1e2e' : '#f5f5f5',
        color: theme === 'dark' ? '#cdd6f4' : '#1e1e2e',
      }}
    >
      <TitleBar />

      <WorkspaceTabBar />

      <main
        className="main-content"
        style={{
          flex: 1,
          overflow: 'hidden',
          position: 'relative',
        }}
      >
        {workspace ? (
          <TerminalGrid />
        ) : (
          <div
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexDirection: 'column',
              gap: '16px',
              color: '#6c7086',
            }}
          >
            <div style={{ fontSize: '48px' }}>📂</div>
            <div style={{ fontSize: '18px', fontWeight: 600 }}>No workspace selected</div>
            <div style={{ fontSize: '14px' }}>
              Create a new workspace to get started
            </div>
            <button
              onClick={() => setWorkspaceModalOpen(true)}
              style={{
                padding: '10px 20px',
                fontSize: '14px',
                fontWeight: 600,
                backgroundColor: '#89b4fa',
                color: '#1e1e2e',
                border: 'none',
                borderRadius: '6px',
                cursor: 'pointer',
                marginTop: '8px',
              }}
            >
              + Create Workspace
            </button>
          </div>
        )}
      </main>

      <footer
        className="status-bar"
        style={{
          padding: '6px 16px',
          backgroundColor: theme === 'dark' ? '#11111b' : '#d0d0d0',
          borderTop: '1px solid #45475a',
          fontSize: '12px',
          color: '#6c7086',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <span>v{appVersion} - Multi-terminal Workspace</span>
        <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
          <span>Ctrl+Tab: Switch Workspace</span>
          <span>Ctrl+PgUp/PgDn: Prev/Next Workspace</span>
          <span>Ctrl+T: Next Terminal</span>
          <button
            onClick={() => setSettingsModalOpen(true)}
            style={{
              padding: '4px 12px',
              fontSize: '12px',
              fontWeight: 600,
              backgroundColor: '#313244',
              color: '#cdd6f4',
              border: '1px solid #45475a',
              borderRadius: '4px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            ⚙️ Settings
          </button>
        </div>
      </footer>

      <WorkspaceSwitcherModal
        isOpen={workspaceSwitcherOpen}
        onClose={() => {
          console.log('[App] Modal onClose called');
          setWorkspaceSwitcherOpen(false);
        }}
        onSelectWorkspace={handleSelectWorkspace}
      />

      <SettingsModal
        isOpen={settingsModalOpen}
        onClose={() => setSettingsModalOpen(false)}
      />
    </div>
  );
}

export default App;

// tdt-space-v3/frontend/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Sidebar,
    StatusBar,
    TitleBar,
    TerminalGrid,
    WorkspaceSwitcherModal,
    SettingsModal,
    WorkspaceCreationModal,
  } from './components';
  import { workspaceStore, initializePlatformInfo } from './stores';
  import { getAppVersion } from './utils/version';
  import { backendAPI } from './services/wails-bridge';
  import { MemoryMonitor } from './lib/memoryMonitor';

  // State
  let workspaceSwitcherOpen = $state(false);
  let settingsModalOpen = $state(false);
  let appVersion = $state('');

  // Derived state
  let theme = $derived(workspaceStore.theme);
  let workspace = $derived(workspaceStore.currentWorkspace);
  let workspaces = $derived(workspaceStore.workspaces);

  // Workspace navigation helpers
  function nextWorkspace() {
    const next = workspaceStore.getNextWorkspace();
    if (next) {
      workspaceStore.setCurrentWorkspace(next);
      return next;
    }
    return null;
  }

  function previousWorkspace() {
    const prev = workspaceStore.getPreviousWorkspace();
    if (prev) {
      workspaceStore.setCurrentWorkspace(prev);
      return prev;
    }
    return null;
  }

  function switchToWorkspaceByIndex(index: number) {
    if (index < 0 || index >= workspaces.length) {
      return null;
    }
    const ws = workspaceStore.getWorkspaceByIndex(index);
    if (ws) {
      workspaceStore.setCurrentWorkspace(ws);
      return ws;
    }
    return null;
  }

  // Keyboard shortcuts handler
  function handleKeyDown(e: KeyboardEvent) {
    // Don't trigger shortcuts when typing in input fields
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
      return;
    }

    // Alt+F4: Close window (for frameless windows on Windows)
    if (e.altKey && e.key === 'F4') {
      e.preventDefault();
      backendAPI.windowClose();
      return;
    }

    // Ctrl+, (comma): Open Settings
    if (e.ctrlKey && e.key === ',') {
      e.preventDefault();
      settingsModalOpen = true;
      return;
    }

    // Ctrl+Shift+N: New workspace
    if (e.ctrlKey && e.shiftKey && e.key === 'N') {
      e.preventDefault();
      workspaceStore.setWorkspaceModalOpen(true);
      return;
    }

    // Ctrl+Tab: Cycle to next workspace with modal preview
    if (e.ctrlKey && e.key === 'Tab') {
      e.preventDefault();
      nextWorkspace();
      workspaceSwitcherOpen = true;
      return;
    }

    // Ctrl+Shift+Tab: Previous workspace
    if (e.ctrlKey && e.shiftKey && e.key === 'Tab') {
      e.preventDefault();
      previousWorkspace();
      workspaceSwitcherOpen = true;
      return;
    }

    // Ctrl+PageUp: Previous workspace
    if (e.ctrlKey && e.key === 'PageUp') {
      e.preventDefault();
      previousWorkspace();
      return;
    }

    // Ctrl+PageDown: Next workspace
    if (e.ctrlKey && e.key === 'PageDown') {
      e.preventDefault();
      nextWorkspace();
      return;
    }

    // Ctrl+T: Next terminal
    if (e.ctrlKey && !e.shiftKey && e.key === 't') {
      e.preventDefault();
      const nextTerminal = workspaceStore.getNextTerminal();
      if (nextTerminal) {
        workspaceStore.setActiveTerminal(nextTerminal.id);
      }
      return;
    }

    // Ctrl+1 through Ctrl+9: Switch to terminal by index
    if (e.ctrlKey && !e.shiftKey && e.key.match(/^[1-9]$/)) {
      e.preventDefault();
      const index = parseInt(e.key) - 1;
      const terminal = workspaceStore.getTerminalByIndex(index);
      if (terminal) {
        workspaceStore.setActiveTerminal(terminal.id);
      }
      return;
    }

    // Ctrl+Shift+T: Previous terminal
    if (e.ctrlKey && e.shiftKey && e.key === 'T') {
      e.preventDefault();
      const prevTerminal = workspaceStore.getPreviousTerminal();
      if (prevTerminal) {
        workspaceStore.setActiveTerminal(prevTerminal.id);
      }
      return;
    }

    // Alt+1 through Alt+9: Switch to workspace by index
    if (e.altKey && e.key.match(/^[1-9]$/)) {
      e.preventDefault();
      const index = parseInt(e.key) - 1;
      switchToWorkspaceByIndex(index);
      return;
    }
  }

  function handleKeyUp(e: KeyboardEvent) {
    if (e.key === 'Control') {
      workspaceSwitcherOpen = false;
    }
  }

  function handleSelectWorkspace(workspaceId: string) {
    const ws = workspaces.find(w => w.id === workspaceId);
    if (ws) {
      workspaceStore.setCurrentWorkspace(ws);
    }
    workspaceSwitcherOpen = false;
  }

  function handleCreateWorkspace() {
    workspaceStore.setWorkspaceModalOpen(true);
  }

  function handleOpenSettings() {
    settingsModalOpen = true;
  }

  // Lifecycle
  onMount(() => {
    // Load app version
    getAppVersion().then(v => appVersion = v);

    // Initialize platform info from backend
    initializePlatformInfo();

    // Load workspaces from store on mount
    workspaceStore.loadWorkspaces();

    // Enable memory monitoring in production to track startup memory spike
    MemoryMonitor.startMonitoring(10000);

    // Log initial memory stats after 5 seconds
    const initialStatsTimeout = setTimeout(() => {
      const stats = MemoryMonitor.getStats();
      if (stats) {
        console.log('[App] Initial memory stats:', {
          usedMB: (stats.usedJSHeapSize / 1024 / 1024).toFixed(2),
          totalMB: (stats.totalJSHeapSize / 1024 / 1024).toFixed(2),
          limitMB: (stats.jsHeapSizeLimit / 1024 / 1024).toFixed(2),
          usagePercent: ((stats.usedJSHeapSize / stats.jsHeapSizeLimit) * 100).toFixed(2) + '%',
        });
      }
    }, 5000);

    // Listen for workspace switcher open event from TerminalCell
    const handleOpenWorkspaceSwitcher = () => {
      workspaceSwitcherOpen = true;
    };
    window.addEventListener('open-workspace-switcher', handleOpenWorkspaceSwitcher);

    return () => {
      MemoryMonitor.stopMonitoring();
      clearTimeout(initialStatsTimeout);
      window.removeEventListener('open-workspace-switcher', handleOpenWorkspaceSwitcher);
    };
  });
</script>

<svelte:window onkeydown={handleKeyDown} onkeyup={handleKeyUp} />

<div
  class="app-container"
  class:dark={theme === 'dark'}
  data-theme={theme}
>
  <TitleBar />

  <div class="app-body">
    <!-- Sidebar Navigation -->
    <Sidebar
      onCreateWorkspace={handleCreateWorkspace}
      onOpenSettings={handleOpenSettings}
    />

    <!-- Main Content Area -->
    <main class="main-content">
      {#if workspaces.length > 0}
        <!-- Header for current workspace -->
        <div class="content-header">
          <div class="workspace-header">
            <span class="header-icon">{workspace?.icon || '📁'}</span>
            <div class="header-info">
              <h1 class="header-title">{workspace?.name || 'Workspace'}</h1>
              <span class="header-meta">
                {workspace?.columns || 0}×{workspace?.rows || 0} layout • {workspace?.terminals?.length || 0} terminals
              </span>
            </div>
          </div>

          <div class="header-actions">
            <button
              class="header-btn"
              onclick={() => {
                if (workspace) {
                  workspaceStore.setWorkspaceModalOpenWithEdit(workspace);
                }
              }}
              title="Edit Layout"
              disabled={!workspace}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
              </svg>
              <span>Edit</span>
            </button>
          </div>
        </div>

        <!-- Render all workspaces, show only active one -->
        <div class="workspaces-container">
          {#each workspaces as ws (ws.id)}
            <div 
              class="workspace-container" 
              class:active={ws.id === workspace?.id}
            >
              <div class="terminal-area">
                <TerminalGrid workspace={ws} isWorkspaceActive={ws.id === workspace?.id} />
              </div>
            </div>
          {/each}
        </div>
      {:else}
        <div class="empty-state">
          <div class="empty-content">
            <div class="empty-icon-wrapper">
              <span class="empty-icon">🚀</span>
            </div>
            <h2 class="empty-title">Welcome to TDT Space</h2>
            <p class="empty-description">
              A multi-agent terminal workspace for AI-powered development.
              <br />
              Create your first workspace to get started.
            </p>
            <button
              class="btn btn-primary btn-lg"
              onclick={handleCreateWorkspace}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
              </svg>
              Create Workspace
            </button>

            <div class="empty-shortcuts">
              <div class="shortcut-hint">
                <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>
                <span>to create workspace</span>
              </div>
              <div class="shortcut-hint">
                <kbd>Ctrl</kbd> + <kbd>,</kbd>
                <span>for settings</span>
              </div>
            </div>
          </div>
        </div>
      {/if}
    </main>
  </div>

  <!-- Status Bar -->
  <StatusBar {appVersion} onOpenSettings={handleOpenSettings} />

  <!-- Modals -->
  <WorkspaceSwitcherModal
    isOpen={workspaceSwitcherOpen}
    onClose={() => workspaceSwitcherOpen = false}
    onSelectWorkspace={handleSelectWorkspace}
  />

  <SettingsModal
    isOpen={settingsModalOpen}
    onClose={() => settingsModalOpen = false}
  />

  <WorkspaceCreationModal
    isOpen={workspaceStore.isWorkspaceModalOpen}
    onClose={() => workspaceStore.setWorkspaceModalOpen(false)}
  />
</div>

<style>
  .app-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    background-color: var(--color-bg-base);
    color: var(--color-text);
  }

  .app-body {
    display: flex;
    flex: 1;
    overflow: hidden;
  }

  .main-content {
    flex: 1;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    min-width: 0;
  }

  /* Content Header */
  .content-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: var(--space-4) var(--space-6);
    border-bottom: 1px solid var(--color-border);
    background-color: var(--color-bg-mantle);
  }

  .workspace-header {
    display: flex;
    align-items: center;
    gap: var(--space-3);
  }

  .header-icon {
    font-size: var(--text-xl);
  }

  .header-info {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
  }

  .header-title {
    font-size: var(--text-lg);
    font-weight: var(--font-semibold);
    color: var(--color-text);
    margin: 0;
    line-height: var(--leading-tight);
  }

  .header-meta {
    font-size: var(--text-xs);
    color: var(--color-text-subtext0);
    font-family: var(--font-mono);
  }

  .header-actions {
    display: flex;
    align-items: center;
    gap: var(--space-2);
  }

  .header-btn {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    padding: var(--space-2) var(--space-3);
    font-size: var(--text-sm);
    font-weight: var(--font-medium);
    color: var(--color-text-subtext1);
    background-color: var(--color-bg-surface0);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .header-btn:hover {
    background-color: var(--color-bg-surface1);
    color: var(--color-text);
    border-color: var(--color-border-hover);
  }

  /* Workspaces Container */
  .workspaces-container {
    flex: 1;
    display: flex;
    overflow: hidden;
    position: relative;
  }

  .workspace-container {
    flex: 1;
    display: none;
    overflow: hidden;
    flex-direction: column;
  }

  .workspace-container.active {
    display: flex;
  }

  /* Terminal Area */
  .terminal-area {
    flex: 1;
    overflow: hidden;
    padding: 2px;
    background-color: var(--color-bg-base);
    display: flex;
  }

  /* Empty State */
  .empty-state {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--space-8);
    background-color: var(--color-bg-base);
  }

  .empty-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: var(--space-6);
    max-width: 480px;
  }

  .empty-icon-wrapper {
    width: 80px;
    height: 80px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, var(--color-bg-surface0), var(--color-bg-surface1));
    border-radius: var(--radius-xl);
    border: 1px solid var(--color-border);
  }

  .empty-icon {
    font-size: 40px;
    filter: drop-shadow(0 0 16px rgba(137, 180, 250, 0.3));
  }

  .empty-title {
    font-size: var(--text-2xl);
    font-weight: var(--font-bold);
    color: var(--color-text);
    margin: 0;
  }

  .empty-description {
    font-size: var(--text-base);
    color: var(--color-text-subtext0);
    line-height: var(--leading-relaxed);
    margin: 0;
  }

  .empty-shortcuts {
    display: flex;
    flex-direction: column;
    gap: var(--space-2);
    margin-top: var(--space-4);
    padding: var(--space-4);
    background-color: var(--color-bg-surface0);
    border-radius: var(--radius-lg);
    border: 1px solid var(--color-border);
  }

  .shortcut-hint {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    font-size: var(--text-sm);
    color: var(--color-text-subtext0);
  }

  .shortcut-hint kbd {
    padding: 2px 6px;
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    background-color: var(--color-bg-surface1);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-xs);
    color: var(--color-text);
  }

  .shortcut-hint span {
    opacity: 0.8;
  }

  /* Button styles */
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--space-2);
    padding: var(--space-2) var(--space-4);
    font-size: var(--text-sm);
    font-weight: var(--font-medium);
    line-height: var(--leading-tight);
    border-radius: var(--radius-md);
    border: 1px solid transparent;
    cursor: pointer;
    transition: all var(--transition-fast) var(--ease-default);
    white-space: nowrap;
    user-select: none;
  }

  .btn-primary {
    background-color: var(--color-primary);
    color: var(--color-bg-base);
  }

  .btn-primary:hover {
    background-color: var(--color-primary-hover);
    transform: translateY(-1px);
    box-shadow: var(--shadow-md);
  }

  .btn-lg {
    padding: var(--space-3) var(--space-6);
    font-size: var(--text-base);
  }

  /* Scrollbar styling for the main content */
  .main-content::-webkit-scrollbar {
    width: 8px;
    height: 8px;
  }

  .main-content::-webkit-scrollbar-track {
    background: transparent;
  }

  .main-content::-webkit-scrollbar-thumb {
    background: var(--color-bg-surface1);
    border-radius: var(--radius-full);
  }

  .main-content::-webkit-scrollbar-thumb:hover {
    background: var(--color-bg-surface2);
  }
</style>
